#!/usr/bin/env python3
"""Generate PLUGINS.md from marketplace.json and each plugin's skill metadata."""

import json
import os
import glob as globmod
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MARKETPLACE = os.path.join(ROOT, ".claude-plugin", "marketplace.json")
OUTPUT = os.path.join(ROOT, "PLUGINS.md")


def parse_skill_frontmatter(path):
    """Extract name and description from SKILL.md YAML frontmatter."""
    with open(path) as f:
        content = f.read()

    if not content.startswith("---"):
        return None

    end = content.index("---", 3)
    frontmatter = content[3:end]

    info = {}
    current_key = None
    for line in frontmatter.splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        # Continuation line (indented) for multi-line values
        if line.startswith("  ") and current_key:
            info[current_key] = info.get(current_key, "") + " " + stripped
            continue
        if ":" in stripped:
            key, _, val = stripped.partition(":")
            key = key.strip()
            val = val.strip().strip('"').strip("'")
            current_key = key if key in ("name", "description") else None
            if current_key:
                # Handle block scalar indicators (>-, |-, >, |)
                if val in (">-", "|-", ">", "|"):
                    info[key] = ""
                else:
                    info[key] = val

    # Clean up whitespace
    for key in info:
        info[key] = " ".join(info[key].split())

    return info if "name" in info else None


def main():
    with open(MARKETPLACE) as f:
        marketplace = json.load(f)

    lines = [
        "# Plugins\n",
        "\n",
        "> This file is auto-generated by `sync/generate_plugin_docs.py`. Do not edit manually.\n",
        "\n",
    ]

    total_plugins = 0
    total_skills = 0

    for entry in sorted(marketplace["plugins"], key=lambda e: e["name"]):
        total_plugins += 1
        plugin_dir = os.path.join(ROOT, entry["source"])
        lines.append(f"## {entry['name']} (v{entry['version']})\n\n")
        lines.append(f"{entry['description']}\n\n")
        lines.append("```\n")
        lines.append(f"/plugin install {entry['name']}@cb-skills\n")
        lines.append("```\n\n")

        # Find skills
        skill_dirs = sorted(globmod.glob(os.path.join(plugin_dir, "skills", "*", "SKILL.md")))
        if skill_dirs:
            lines.append("### Skills\n\n")
            lines.append("| Skill | Description |\n")
            lines.append("|-------|-------------|\n")
            for skill_path in skill_dirs:
                total_skills += 1
                info = parse_skill_frontmatter(skill_path)
                if info:
                    skill_id = os.path.basename(os.path.dirname(skill_path))
                    desc = info.get("description", "")
                    lines.append(f"| `/{skill_id}` | {desc} |\n")
            lines.append("\n")

        lines.append("---\n\n")

    lines.append(f"*{total_plugins} plugin(s), {total_skills} skill(s)*\n")

    with open(OUTPUT, "w") as f:
        f.writelines(lines)

    print(f"PLUGINS.md generated: {total_plugins} plugin(s), {total_skills} skill(s)")


if __name__ == "__main__":
    main()
